name: Continuous Integration

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade html-testRunner

      - name: Install Selenium Standalone Server and Chrome Driver
        uses: nanasess/setup-chromedriver@master
        with:
          chromedriver-version: 'latest'

      - name: Install GeckoDriver
        uses: nanasess/setup-geckodriver@master
        with:
          geckodriver-version: 'latest'

      - name: Get Chrome version
        run: chrome --version

      - name: Get Firefox version
        run: firefox --version

      - name: Start Selenium Server HUB
        run: Start-Process -NoNewWindow -FilePath "java" -ArgumentList "-jar selenium-server-4.17.0.jar", "--port 4445 hub"
        shell: pwsh

      - name: Start Selenium Server nodes
        run: Start-Process -NoNewWindow -FilePath "java" -ArgumentList "-jar selenium-server-4.17.0.jar", "node"
        shell: pwsh

      - name: Run tests
        run: |
          python tests/test_api_test_delete_goal_api.py

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: test-reports/**/*.html
