name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]
        # Add or remove python versions as needed
        # Optionally, include other dimensions such as operating system

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-xdist  # Ensure pytest-xdist is installed

    - name: Run tests with pytest and generate report
      run: |
        python -m pytest -n auto tests/test_generate_tests --html=report.html --self-contained-html
      # The -n auto option automatically determines the number of workers

    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Test-Reports
        path: report.html
